### ISSUE TITLE
Failed to upgrade wmill from v1.387.0 to version v1.397.4

### ISSUE THREAD

**Issue by abhi1693** [windmill-labs/windmill-deno-client#1]
```
✅ Granted all run access.
error: Module not found "https://deno.land/x/wmill@v1.397.4/gen/services.gen.ts".
    at https://deno.land/x/wmill@v1.397.4/flow.ts:5:24
error: Uncaught (in promise) Error: Failed to upgrade wmill from v1.387.0 to version v1.397.4!
      throw new Error(
            ^
    at DenoLandProvider.upgrade (https://deno.land/x/cliffy@v1.0.0-rc.4/command/upgrade/provider.ts:120:13)
    at eventLoopTick (ext:core/01_core.js:169:7)
    at async UpgradeCommand.actionHandler (https://deno.land/x/cliffy@v1.0.0-rc.4/command/upgrade/upgrade_command.ts:75:11)
    at async UpgradeCommand.execute (https://deno.land/x/cliffy@v1.0.0-rc.4/command/command.ts:1937:7)
    at async UpgradeCommand.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.4/command/command.ts:1769:14)
    at async https://deno.land/x/wmill@v1.387.0/main.ts:158:3
```

**Comment by rubenfiszel** [comment]
It's not the right repo, you had an issue upgrading the CLI. We will fix this, but please use npm now if you can:
`deno uninstall wmill && npm install -g windmill-cli`
